name: Reusable - CI Service Pull Request Scan

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      service-path:
        required: true
        type: string
      sast-path:
        required: false
        default: ""
        type: string
      runtime:
        required: false
        default: python
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      SNYK_TOKEN:
        required: true

jobs:
  sast:
    uses: ./.github/workflows/_sast.yml
    with:
      service-path: ${{ inputs.sast-path != '' && inputs.sast-path || inputs.service-path }}
      fail-on-quality-gate: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sca:
    needs: [sast]
    uses: ./.github/workflows/_sca.yml
    with:
      service-name: ${{ inputs.service-name }}
      service-path: ${{ inputs.service-path }}
      runtime: ${{ inputs.runtime }}
      severity-threshold: high
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  pr-comment:
    needs: [sast, sca]
    if: always()
    uses: ./.github/workflows/_pr-comment.yml
    with:
      service-name: ${{ inputs.service-name }}
      sast: ${{ needs.sast.result }}
      sca: ${{ needs.sca.result }}
      trivy: skipped
